jQuery(document).ready(function(e){
 var check_counts=false;if(jQuery('.s2s_fb_like_count').val()=="1"||jQuery('.s2s_fb_share_count').val()=="1"||jQuery('.s2s_fb_total_count').val()=="1"){check_counts=true;}
if(jQuery('.s2s_pinterest_count').val()=="1")check_counts=true;if(jQuery('.s2s_linkedin_count').val()=="1")check_counts=true;if(jQuery('.s2s_gplus_b_count').val()=="1")check_counts=true;if(jQuery('.s2s_tumblr_count').val()=="1")check_counts=true;if(jQuery('.s2s_vk_count').val()=="1")check_counts=true;if(check_counts){var init_donreach=false;var data_donreach;jQuery('.social2s_url').each(function(index){var s2s_url=jQuery(this).val(); if(jQuery('.s2s_fb_like_count').val()=="1"||jQuery('.s2s_fb_share_count').val()=="1"||jQuery('.s2s_fb_total_count').val()=="1"){var s2s_fb_count_share=jQuery(this).parent().find('.s2s_fb_count_share');var s2s_fb_count_like=jQuery(this).parent().find('.s2s_fb_count_like');var s2s_fb_count_hide=jQuery('.s2s_fb_count_hide').val();
jQuery.getJSON('//graph.facebook.com/?id='+s2s_url+'&format=json',function(data){if(s2s_fb_count_hide=='1'){if(data.share.share_count!='0'){s2s_fb_count_share.text(data.share.share_count);}else{s2s_fb_count_share.remove();}
if(data.share.comment_count!='0'){s2s_fb_count_like.text(data.share.comment_count);}else{s2s_fb_count_like.remove();}
}else{s2s_fb_count_share.text(data.share.share_count);s2s_fb_count_like.text(data.share.comment_count);}});}
 
if(jQuery('.s2s_pinterest_count').val()=="1"){var s2s_pinterest_count=jQuery(this).parent().find('.s2s_pinterest_badge_count');var pin='https://api.pinterest.com/v1/urls/count.json?callback=?';jQuery.getJSON(pin,{url:s2s_url,}).done(function(data){var s2s_pinterest_count_hide=jQuery('.s2s_pinterest_count_hide').val();if(s2s_pinterest_count_hide=='1'){if(data.count!='0'){s2s_pinterest_count.text(data.count);}else{s2s_pinterest_count.remove();}}else{s2s_pinterest_count.text(data.count);}});}
 
if(jQuery('.s2s_linkedin_count').val()=="1"){var s2s_linkedin_count=jQuery(this).parent().find('.s2s_linkedin_badge_count');jQuery.ajax({dataType:"jsonp",url:"https://www.linkedin.com/countserv/count/share",data:{callback:"?",format:"jsonp",url:s2s_url}}).done(function(data){var s2s_linkedin_count_hide=jQuery('.s2s_linkedin_count_hide').val();if(s2s_linkedin_count_hide=='1'){if(data.count!='0'){s2s_linkedin_count.text(data.count);}else{s2s_linkedin_count.remove();}}else{s2s_linkedin_count.text(data.count);}});} 
if(jQuery('.s2s_tumblr_count').val()=="1"){var s2s_tumblr_count=jQuery(this).parent().find('.s2s_tumblr_badge_count');var pin='http://api.tumblr.com/v2/share/stats';jQuery.getJSON(pin,{url:s2s_url,}).done(function(data){var s2s_tumblr_count_hide=jQuery('.s2s_tumblr_count_hide').val();if(s2s_tumblr_count_hide=='1'){if(data.count!='0'){s2s_tumblr_count.text(data.count);}else{s2s_tumblr_count.remove();}}else{s2s_tumblr_count.text(data.count);}});}
if(jQuery('.s2s_vk_count').val()=="1"||jQuery('.s2s_gplus_b_count').val()=="1"){
if(init_donreach){return;}
var s2s_gplus_b_count=jQuery(this).parent().find('.s2s_gplus_b_badge_count');var s2s_vk_count=jQuery(this).parent().find('.s2s_vk_badge_count');jQuery.ajax({dataType:"jsonp",crossDomain:true,url:"https://count.donreach.com/?url="+s2s_url+"&providers=google,vk"}).done(function(data){ if(jQuery('.s2s_gplus_b_count').val()=="1"){var s2s_gplus_b_count_hide=jQuery('.s2s_gplus_b_count_hide').val();if(s2s_gplus_b_count_hide=='1'){if(data.shares.google!='0'){s2s_gplus_b_count.text(data.shares.google);}else{s2s_gplus_b_count.remove();}}else{s2s_gplus_b_count.text(data.shares.google);}} 
if(jQuery('.s2s_vk_count').val()=="1"){var s2s_vk_count_hide=jQuery('.s2s_vk_count_hide').val();if(s2s_vk_count_hide=='1'){if(data.shares.vk!='0'){s2s_vk_count.text(data.shares.vk);}else{s2s_vk_count.remove();}}else{s2s_vk_count.text(data.shares.vk);}}});init_donreach=true;}});}
if(jQuery('.s2s_k2_remove_social').val()=="1"){if(jQuery('.itemSocialSharing').length>=1){jQuery('.itemSocialSharing').remove();}}
jQuery('.s2s_mas').click(function(e){if(jQuery(this).hasClass('s2s_mas_opened')){jQuery(this).removeClass('s2s_mas_opened').removeClass('active');jQuery(this).parent().children('.afterplus').removeClass('afterplus_open');jQuery(this).children('a').children('.fa-minus-circle').removeClass('fa-minus-circle').addClass('fa-plus-circle');}else{jQuery(this).addClass('s2s_mas_opened').addClass('active');jQuery(this).parent().children('.afterplus').addClass('afterplus_open');jQuery(this).children('a').children('.fa-plus-circle').removeClass('fa-plus-circle').addClass('fa-minus-circle');}}); if(jQuery('.social2s_load_social_scripts').val()=="1"){load_social_scripts();}else if(jQuery('.social2s_load_social_scripts').val()=="2"){if(jQuery('.social2s_context').val()=="com_content.article"){load_social_scripts();}} 
if(jQuery('.s2s_pos_fixed').length>=1){var ancho_total=jQuery(window).width();var ancho_defined=jQuery('.s2s_art_mobile_min').val();if(ancho_total<=ancho_defined){ jQuery('.s2s_supra_contenedor').removeClass('s2s_pos_fixed');jQuery('.s2s_supra_contenedor').removeClass('s2s_fixed_vertical');jQuery('.s2s_contenedor').addClass('btn-group').removeClass('btn-group-vertical');}} 
var s2s_insert=jQuery('.s2s_insert').html();var s2s_context=jQuery('.social2s_context').val();if(s2s_insert=="1"&&s2s_context=='com_content.article'&&jQuery('.s2s_insert_element').html()!=''){var s2s_clase='.'+jQuery('.s2s_insert_element').html(); if(jQuery(s2s_clase).length){ jQuery('.s2s_vk script').html('');var s2s_element=jQuery(s2s_clase);var contenidos=jQuery('.s2s_supra_contenedor').html();var s2s_insert_position=jQuery('.s2s_insert_position').html();if(s2s_insert_position=="0"){s2s_element.before('<div class="s2s_supra_contenedor_dummy"></div>');}else if(s2s_insert_position=="1"){s2s_element.after('<div class="s2s_supra_contenedor_dummy"></div>');}else if(s2s_insert_position=="2"){s2s_element.prepend('<div class="s2s_supra_contenedor_dummy"></div>');}else if(s2s_insert_position=="3"){s2s_element.append('<div class="s2s_supra_contenedor_dummy"></div>');}else{s2s_element.after('<div class="s2s_supra_contenedor_dummy"></div>');}
jQuery('.s2s_supra_contenedor_dummy').append(contenidos); jQuery('.s2s_supra_contenedor').html('');}}
jQuery('.s2s_twitter').click(function(e){buttons(this);if(checkCookie())twitter();if(jQuery('.twitter-follow-button').length>=1){jQuery('.s2s_twitter_iframe').css('min-width','270px');}});jQuery('.s2s_facebook').click(function(e){buttons(this);if(checkCookie())facebook();});jQuery('.s2s_pinterest').click(function(e){buttons(this);if(checkCookie())pinterest();});jQuery('.s2s_linkedin').click(function(e){buttons(this);if(checkCookie())linkedin(this);});jQuery('.s2s_gplus').click(function(e){buttons(this);if(checkCookie())gplus();});jQuery('.s2s_wapp').click(function(e){buttons(this);if(checkCookie())gplus();});jQuery('.s2s_tumblr').click(function(e){buttons(this);if(checkCookie())tumblr();});jQuery('.s2s_vk').click(function(e){buttons(this);if(checkCookie())vk(this);});jQuery('.s2s_cookie_contenedor').click(function(e){e.stopPropagation();cookieAccept();var globo=jQuery(this).parent('div');is_on_screen(globo);var callSocialFunction=jQuery(this).parent();if(callSocialFunction.hasClass('s2s_twitter_iframe')){twitter();}else if(callSocialFunction.hasClass('s2s_facebook_iframe')){facebook();}else if(callSocialFunction.hasClass('s2s_pinterest_iframe')){pinterest();}else if(callSocialFunction.hasClass('s2s_linkedin_iframe')){linkedin();}else if(callSocialFunction.hasClass('s2s_gplus_iframe')){gplus();}else if(callSocialFunction.hasClass('s2s_tumblr_iframe')){tumblr();}else if(callSocialFunction.hasClass('s2s_vk_iframe')){vk();}});jQuery('.s2s_cookie_information').click(function(e){e.stopPropagation();jQuery('.s2s_cookie_more_info').toggle('slow',function(e){});}); jQuery('.s2s_cookie_read_policy a').click(function(e){e.stopPropagation();});jQuery('.s2s_cookie_copyright a').click(function(e){e.stopPropagation();});function buttons(boton){var globo=jQuery(boton).children('div'); if(jQuery('.s2smodern').length>=1){if(jQuery(boton).hasClass('active')){jQuery(boton).removeClass('active');}else{jQuery('.s2s_contenedor > div').removeClass('active');jQuery(boton).addClass('active');is_on_screen(globo);}
}else{if(jQuery(boton).hasClass('active')){jQuery(boton).removeClass('active');globo.fadeTo(330,0,function(){globo.hide();});}else{jQuery('.s2s_contenedor > div').removeClass('active');jQuery('.globo').hide();jQuery(boton).addClass('active');globo.fadeTo(330,1,function(){});is_on_screen(globo);}}}
function twitter(){if(!jQuery('.s2s_twitter_iframe').hasClass('s2s_loaded')){jQuery('.s2s_twitter_iframe').addClass("s2s_loaded"); if(jQuery('.s2s_btn_twitter').length>=1){}else{!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','twitter-wjs');}
!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','twitter-wjs');}else{var tw_globo=jQuery('.s2s_twitter_iframe').width();var tw_iframe=jQuery('.s2s_twitter_iframe iframe').width()+40;jQuery('.s2s_twitter_iframe').css('width',tw_iframe+'px');}}
function facebook(){if(!jQuery('.s2s_facebook_iframe').hasClass('s2s_loaded')){jQuery('.s2s_facebook_iframe').addClass("s2s_loaded");var language=jQuery('.social2s_lang_1tag').val();(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="//connect.facebook.net/"+language+"/sdk.js#xfbml=1&appId=514279921989553&version=v2.6";fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk'));}}
function pinterest(){if(!jQuery('.s2s_pinterest_iframe').hasClass('s2s_loaded')){jQuery('.s2s_pinterest_iframe').addClass("s2s_loaded");(function(d){var f=d.getElementsByTagName('SCRIPT')[0],p=d.createElement('SCRIPT');p.type='text/javascript';p.async=true;p.src='//assets.pinterest.com/js/pinit.js';f.parentNode.insertBefore(p,f);}(document));}}
function linkedin(este){if(!jQuery('.s2s_linkedin_iframe').hasClass('s2s_loaded')){ if(jQuery('.social2s_context').val()=="com_content.article"){jQuery('.s2s_linkedin_iframe').addClass("s2s_loaded");}
var language=jQuery('.social2s_lang_1tag').val();var linkedin_art_path=jQuery(este).children('.linkedin_art_path').val();jQuery.getScript("https://platform.linkedin.com/in.js?async=true",function success(){IN.init({lang:language});});}}
function gplus(){if(!jQuery('.s2s_gplus_iframe').hasClass('s2s_loaded')){jQuery('.s2s_gplus_iframe').addClass("s2s_loaded");var language=jQuery('.s2s_gplus').attr('lang');window.___gcfg={lang:language};(function(){var po=document.createElement('script');po.type='text/javascript';po.async=true;po.src='https://apis.google.com/js/plusone.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(po,s);})();}}
function tumblr(){if(!jQuery('.s2s_tumblr_iframe').hasClass('s2s_loaded')){jQuery('.s2s_tumblr_iframe').addClass("s2s_loaded");
!function(d,s,id){var js,ajs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://secure.assets.tumblr.com/share-button.js";ajs.parentNode.insertBefore(js,ajs);}}(document,"script","tumblr-js");}}
function vk(clikon){if(!jQuery('.s2s_vk_iframe').hasClass('s2s_loaded')){jQuery('.s2s_vk_iframe').addClass("s2s_loaded");
 if(clikon){ if(jQuery('.vk_button').length>=1){var vk_boton_id=jQuery(clikon).children('.globo').children('.vk_button').attr('id');VK.Widgets.Like(vk_boton_id);}}}}
function checkCookie(){var checkCookie=jQuery('.checkCookie').text().split("")[0]; if(checkCookie=="1"){var s2s_cookie=getCookie("s2s_cookie");var ccm_cookie=getCookie("ccm_cookies_accepted");var gear_cookie=getCookie("gearcookies");var folcomedia_cookie=getCookie("fmalertcookies");var jb_cookie=getCookie("jbcookies");var crayon_cookieaccept=getCookie("cookieaccept");
if((s2s_cookie!=null&&s2s_cookie!="")||(ccm_cookie!=null&&ccm_cookie=="yes")||(gear_cookie!=null&&gear_cookie=="yes")||(folcomedia_cookie!=null&&folcomedia_cookie=="true")||(jb_cookie!=null&&jb_cookie=="yes")||(crayon_cookieaccept!=null&&crayon_cookieaccept=="yes")){jQuery('.s2s_cookie_contenedor').hide();return true;}else{jQuery('.s2s_cookie_contenedor').show();return false;}}else{return true;}}
function setCookie(c_name,value,exdays){var exdate=new Date();exdate.setDate(exdate.getDate()+exdays);var c_value=escape(value)+((exdays==null)?"":"; expires="+exdate.toUTCString());document.cookie=c_name+"="+c_value;}
function getCookie(c_name){var c_value=document.cookie;var c_start=c_value.indexOf(" "+c_name+"=");if(c_start==-1){c_start=c_value.indexOf(c_name+"=");}
if(c_start==-1){c_value=null;}else{c_start=c_value.indexOf("=",c_start)+1;var c_end=c_value.indexOf(";",c_start);if(c_end==-1){c_end=c_value.length;}
c_value=unescape(c_value.substring(c_start,c_end));}
return c_value;}
function cookieAccept(){setCookie("s2s_cookie",1,365);jQuery('.s2s_cookie_contenedor').hide();jQuery('.s2s_supra_contenedor').removeClass('cookie_on');}
function load_social_scripts(){if(jQuery('.s2s_twitter').length>=1){twitter();}
if(jQuery('.s2s_facebook').length>=1){facebook();}
if(jQuery('.s2s_pinterest').length>=1){pinterest();}
if(jQuery('.s2s_linkedin').length>=1){linkedin(jQuery('.s2s_linkedin'));}
if(jQuery('.s2s_gplus').length>=1){gplus();}
if(jQuery('.s2s_tumblr').length>=1){tumblr();}
if(jQuery('.s2s_vk').length>=1){vk();}}
if(jQuery('.s2s_cta_active').val()==1){jQuery('.s2s_cta_wrapper .s2s_supra_contenedor').removeClass('s2s_pos_fixed');jQuery('.s2s_cta_wrapper .s2s_supra_contenedor').removeClass('s2s_fixed_vertical');jQuery('.s2s_cta_wrapper .s2s_contenedor').addClass('btn-group').removeClass('btn-group-vertical'); jQuery('.s2s_cta_close').click(function(e){jQuery('.s2s_cta_active').val('0'); jQuery('.s2s_cta_wrapper').removeClass('s2s_cta').delay(1000).queue(function(){jQuery(this).remove();}); if(getCookie("s2s_cta_close")==null){setCookie("s2s_cta_close",1,365);}else if(getCookie("s2s_cta_close")=="1"){setCookie("s2s_cta_close",2,365);}});if(jQuery('.s2s_cta_wrapper').length>=1){if(jQuery('.s2s_cta_wrapper').hasClass('cta_pos_right')){jQuery('.s2s_cta_wrapper .globo').addClass('is_on_screen');}}
var _throttleTimer=null;var _throttleDelay=100;var _th_nearend=false;function ScrollHandler(e){if(jQuery('.s2s_cta_active').val()==0){return;}
clearTimeout(_throttleTimer);_throttleTimer=setTimeout(function(){ if(jQuery(window).scrollTop()+jQuery(window).height()>jQuery(document).height()-100){if(_th_nearend==false){jQuery('.s2s_cta_wrapper').addClass('s2s_cta'); jQuery('.s2s_cta_wrapper .s2s_supra_contenedor .btn').removeClass('btn-lg').removeClass('btn-xs').removeClass('btn-sm');cta_default_social();_th_nearend=true;}}else if(_th_nearend==true){_th_nearend=false;jQuery('.s2s_cta_wrapper').removeClass('s2s_cta');cta_default_social();}},_throttleDelay);}
jQuery(window).off('scroll',ScrollHandler).on('scroll',ScrollHandler);} 
function cta_default_social(){var cta_def=jQuery('.s2s_cta_default').val();if(jQuery('.s2s_cta_wrapper').length<=0){return;}
if(cta_def=='0'){}else if(cta_def=='twitter'){buttons(jQuery('.s2s_cta_wrapper .s2s_twitter'));if(checkCookie())twitter();}else if(cta_def=='facebook'){buttons(jQuery('.s2s_cta_wrapper .s2s_facebook'));facebook();}else if(cta_def=='pinterest'){buttons(jQuery('.s2s_cta_wrapper .s2s_pinterest'));pinterest();}else if(cta_def=='linkedin'){buttons(jQuery('.s2s_cta_wrapper .s2s_linkedin'));linkedin();}else if(cta_def=='gplus'){buttons(jQuery('.s2s_cta_wrapper .s2s_gplus'));gplus();}else if(cta_def=='wapp'){buttons(jQuery('.s2s_cta_wrapper .s2s_wapp'));}else if(cta_def=='tumblr'){buttons(jQuery('.s2s_cta_wrapper .s2s_tumblr'));tumblr();}else if(cta_def=='vk'){buttons(jQuery('.s2s_cta_wrapper .s2s_vk'));vk();}}
function is_on_screen(objeto){ if(jQuery('.s2s_supra_contenedor').hasClass('s2s_pos_fix_x_right')){return;}
var obj_x=objeto.offset().left;var obj_y=objeto.offset().top; var obj_w=jQuery(objeto).outerWidth(); var obj_h=jQuery(objeto).outerHeight(); if(obj_w>=obj_x){var resta_prevent_left=obj_w-obj_x;}else{var resta_prevent_left=0;} 
var window_w=jQuery(window).width(); var window_h=jQuery(window).height();var suma_obj_x=obj_x+obj_w;var suma_obj_y=obj_y+obj_h;var button_w=jQuery(objeto).parent('div.btn').children('a').outerWidth();var preventX=(obj_w-button_w)*-1;if(suma_obj_x<0){}else if(suma_obj_y<0){}else if(suma_obj_x>window_w){objeto.css('left',preventX+resta_prevent_left);objeto.addClass('is_on_screen');}else if(suma_obj_y>window_h){ if(objeto.parents('.s2s_cta_wrapper').length>=1){objeto.css('left','inherit');objeto.removeClass('is_on_screen');}}else{objeto.css('left','inherit');objeto.removeClass('is_on_screen');}
boton_w=(jQuery(objeto).parent().width()-16)/2;flecha_w=jQuery(objeto).parent().children('.s2s_flecha').width();if(objeto.hasClass('is_on_screen')){objeto.children('.s2s_flecha').css('right',boton_w+resta_prevent_left+'px');objeto.children('.s2s_flecha').css('left','');}else{objeto.children('.s2s_flecha').css('left',boton_w+'px');objeto.children('.s2s_flecha').css('right','');}}});